# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\"%\n\x06Number\x12\x0c\n\x04\x64ict\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x32\x84\x01\n\x05\x42\x61nk1\x12\x1b\n\x05query\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1d\n\x07\x64\x65posit\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1e\n\x08withdraw\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1f\n\tpropogate\x12\x07.Number\x1a\x07.Number\"\x00\x32\x84\x01\n\x05\x42\x61nk2\x12\x1b\n\x05query\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1d\n\x07\x64\x65posit\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1e\n\x08withdraw\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1f\n\tpropogate\x12\x07.Number\x1a\x07.Number\"\x00\x62\x06proto3'
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dict', full_name='Number.dict', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)



_BANK1 = _descriptor.ServiceDescriptor(
  name='Bank1',
  full_name='Bank1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=57,
  serialized_end=189,
  methods=[
  _descriptor.MethodDescriptor(
    name='query',
    full_name='Bank1.query',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deposit',
    full_name='Bank1.deposit',
    index=1,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='withdraw',
    full_name='Bank1.withdraw',
    index=2,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='propogate',
    full_name='Bank1.propogate',
    index=3,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANK1)

DESCRIPTOR.services_by_name['Bank1'] = _BANK1


_BANK2 = _descriptor.ServiceDescriptor(
  name='Bank2',
  full_name='Bank2',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=192,
  serialized_end=324,
  methods=[
  _descriptor.MethodDescriptor(
    name='query',
    full_name='Bank2.query',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deposit',
    full_name='Bank2.deposit',
    index=1,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='withdraw',
    full_name='Bank2.withdraw',
    index=2,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='propogate',
    full_name='Bank2.propogate',
    index=3,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANK2)

DESCRIPTOR.services_by_name['Bank2'] = _BANK2

# @@protoc_insertion_point(module_scope)
